js_beginning/js_intro.md

Intro to JS with basic challenges for Day 1

First day notes and challenges updated

---

js_beginning/js_arrays.md
tools_and_resources/atom.md
tools_and_resources/terminal.md

Added two files to the tools folder in the syllabus. One with terminal info and one with atom info. Still need info for command line on windows machines.

Sarah terminal

---

README.md
js_beginning/01js_intro.md
js_beginning/02js_conditions.md
js_beginning/03js_functions.md
js_beginning/04js_arrays.md
js_beginning/05js_loops.md
js_beginning/06js_funcLoopsArrays.md
js_beginning/07js_objects.md

Adds index to first Javascript Unit topics and links within lessons

Add unit structure

---

ruby/05rb_rspec.md
ruby/06rb_bdd_car_challenge.md
ruby/06rb_testing.md

added video links and challenges to testing and rspec files.

---

sql/08rails_sql_joins.md

fixes some references to the new image locations

Add join images

---

README.md

Reverts LEARNAcademy/Syllabus#87

Revert "fix tic tac toe link"

---

React_and_Rails_Cat_Tinder/Frontend/05cat_tinder_cats.md
React_and_Rails_Cat_Tinder/Frontend/06cat_tinder_new_cats.md

updates bootstrap component references

React bootstrap updates

---

devise-authentication/README.md

replaces gh classroom assignment links with generic repo links

replace gh classroom links

---

README.md

round two of edits

---

README.md
tools_and_resources/how_the_internet_works_intro.md

How the internet works lecture and added link to Unit Two in the TOC

Add internet lecture

---

README.md

fix front page links

---

README.md
react/react_component_lifecycle.md

a first draft to component lifecycle content

Add react lifecycle

---

js_beginning/02js_conditions.md

Changed Video

---

js_beginning/02js_conditions.md

added epic challenge

---

js_beginning/03js_functions.md
js_beginning/07js_objects.md
react/04react_state.md

addresses #21 
This addresses:
* wording of pluralizer (make sure to add that user will input a number and a singular noun)
* switched the order as suggested to match input order
* langauge challenge - default being english
* Added a link about js default params
*  exercise 2 and 4 on objects lesson - clearer directions
* minor text changes to hopefully make it a bit clearer
Which leaves the following:
* These 2 have been fixed already: 
* 'typeOf()' on the functions loops arrays should be 'typeof'
* reword magic8 ball "variable set to question..."
I'm not sure what this means: typeof challenge (conditions day)

21 - challenge changes

---

React_and_Rails_Cat_Tinder/Frontend/04routing-in-react/04-recipes-challenge.md

Hopefully fixes #147. Not entirely sure where the bold markdown should end for the side note on line 5, so I just had it encompass the whole paragraph

140 - styling on recipe challenge

---

sql/07rails_intro_postgres.md

Move subquery (with) challenges to Stretch Challenges section

Move subquery challenges to Stretch Challenges

---

Rails-C&V/07rails_miniprojects.md
tools_and_resources/intro_to_programming.md

Update rails miniprojects

---

Rails-C&V/05rails_forms.md

Adds Ruby Review Video to Rails Forms

adds ruby review video

---

README.md
tools_and_resources/portfolio.md

adds brief portfolio intro to tools and resources folder and link in README during unit 3

adds portfolio resources

---

react/intro.md
react/nested-components.md

- Adds intro overview
- Adds learning objectives to nested components

React updates sp

---

javascript/arrays.md
javascript/class-inheritance.md
javascript/classes.md
javascript/conditionals.md
javascript/functions-loops-arrays.md
javascript/functions.md
javascript/higher-order-functions.md
javascript/intro.md
javascript/jest.md
javascript/loops.md
javascript/objects.md
javascript/spread-operator.md
javascript/template-literals.md
tools_and_resources/assessments.md

- adds overview to each section
- adds learning objectives to each section
- adds vocabulary list to each section
- adds file set up to each section
- adds examples to jest file
- adds more examples to map and filter
- adds examples to functions

Js intro updates sp

---

README.md
javascript/conditionals.md
react/forms.md
react/functional-props.md

Added lesson for functional props to fall between props (dice challenge) and react mob projects.

Functional props

---

rails_fullstack/forms.md
rails_fullstack/strong_parameters.md
rails_fullstack/wildlife_tracker_challenge.md

Added form_with functionality with form helper methods

Rails forms

---

cat-tinder/frontend/jest-enzyme.md

Added three additional bullet points for Jest and Enzyme challenges (Cat Tinder).
Added instructions to create an additional test folder
Added instructions to create tests to check for render of each page and component by finding a single element.

Add 3 extra challenges to Jest/Enzyme

---

tools_and_resources/terminal.md

Made changes to various formatting for ease of understanding.
Capitalized names.
Re-worded the "Up arrow last command" to "Repeat a previous command without typing it".
Provided examples for Terminal Commands.

Made formatting changes and reworded some challenges.

---

capstone/modifying-devise.md
capstone/prep-checklist.md
capstone/requirements.md
capstone/schedule.md

From Trello card: Create Capstone Planning Checklist
- adds checklist and moves items from schedule into checklist
Adds section for modifying Devise views
- adding column
- adding strong params
- styling
- adding bootstrap

Devise views

---

ruby/hashes.md

- updates appropriate syntax for hashes
- adds CRUD functionality for hash operations
- adds section on enumerals and duck typing
- removes content about string vs symbol
- adds challenges

expands hashes section and adds challenges

---

README.md
rails_model/active_record_intro.md
rails_model/seeds.md

- adds "syllabus short" seeds to week 5 section
- updates TOC links
- reworks content for active record intro

Ar intro seeds

---

rails_fullstack/fullstack.md
rails_fullstack/strong_parameters.md

- add the instance variable to new controller method
- uses instance variable in the form_with method
- adds strong params require

updates strong params for rails forms

---

rails_fullstack/fullstack.md

- replaces blog post example with another example
- restructures the flow of the data
- adds more content for `as` alias and `link_to`

add clarity and improved example of full-stack rails

---

README.md
cat-tinder/backend/api_intro.md
cat-tinder/connecting/fetch-create.md
cat-tinder/connecting/fetch-delete.md
cat-tinder/connecting/fetch-read.md
cat-tinder/connecting/fetch-update.md
cat-tinder/frontend/cat-create.md
cat-tinder/frontend/cat-update.md
cat-tinder/frontend/intro.md
cat-tinder/frontend/jest-enzyme.md

- Distinguished edit from update in appropriate places
- Refactor to limit the use of `componentDidMount` 
- Fixes fetch call success for edit functionality
- Small refactor for fetch call flow

small refactors for cat tinder

---

ruby/inheritance.md

still haven't added attr_accessor ill let you know once it up ;)

remove relations, rework some language

---

ruby/methods.md

I updated the language to be more consistent with user and developer stories. hopefully it makes the challenge a little clearer. let me know if I should add or adjust anything else

update language for PW checker

---

javascript/higher-order-functions.md
javascript/jest.md

- Added `yarn add jest` to useful commands
- Updated formatting of additional resources
- Added Jest Matchers documentation
- Cleaned up and clarified set-up steps.
- Cleaned up formatting of each section of existing text.
- Added breaks between each section.
- Added additional information to syntax bullet points.
- Added matcher information and doc link to syntax bullet points.
- Moved description of the first example test to above the example.
- Added pseudo coding to the first example test to describe each line below it.
- Added explanation of the anatomy of a jest test
- Added shell highlighting to each jest test run
- Expanded on how to read a jest test failure and its error message.
- Moved a comment out of the test highlighting and into its own notice.
- Added a notice to not …

Jest edits

---

javascript/higher-order-functions.md

After noticing some confusion through cohorts on the challenges section, I've decided to enrich the entire page with some easier to differentiate sections and instruction formatting.
- Added separators between each challenge
- Added easier to read variables and expected outcomes
- List format of challenges
- Made the map vs filter section a bit easier to understand.
- Highlighted requirements of challenges and reminders.
- Some small various bolding and italicizing

Enriched formatting on entire page

---

javascript/higher-order-functions.md

Made minor changes as per Sarah's recommendation.

Added recommended changes

---

javascript/functions.md

changed function declaration to function expression; add function signature; updated example formatting to be clearer

Update some vocab

---

javascript/arrays.md
javascript/functions.md

- fixes markdown in arrays
- total rework of functions section

adds arrays and functions syllabus section rework

---

javascript/functions.md
javascript/intro.md

- intro overhaul
- fixes markdown in functions

adds js intro build out

---

cat-tinder/connecting/fetch-delete.md
postgresql/queries.md
ruby/classes_objects.md

Hi Sarah, I ran into this while working on the fetch delete in the tinder project. I believe that the instructions should be directing us to pass the deleteCat method through the show route (that is in the src/App.js file and not in the src/pages/CatShow.js) so that our CatShow component has access to the method. I thought that this could potentially create some confusion in the future.

Folder path typo

---

javascript/conditionals.md
javascript/intro.md

- Updating external links to open in a new tab, realizing that just doesn't work, undoing said work
- Adds more recent video to conditionals
- Denotes specific vocab words
- Adds new learning objectives

Conditionals

---

rails/wildlife-tracker-challenge.md

adds datetime example and refers to params section

updates syllabus to include datetime example and params reference

---

rails/controllers-routes-views.md

- Clean up on the Rails CRV challenges after combining the params section.
- Students noted the verbiage on the challenges was confusing.
- Separated the CRV and params challenge sections for clarity.

updates params challenges based on student feedback

---

javascript/loops.md

cleans up markdown syntax in loops challenges

---

github/assessments.md
github/github.md
github/pairing-with-github.md

Changes all `git add .` to `git add <file-name>`

modifies git add commands

---

README.md

Fixed an issues where some links in the Unit 3 React section of the Syllabus were not working correctly in VSCode.

fixed Unit 3 React links to work with VSCode

---

capstone/requirements.md

- Adds the Bravo demo video to the demo instructions
- Cleans up and clarifies some language on requirements

adds excellent demo video as an example

---

react/functional-props.md

- new code example
- uses an array of objects in state
- adds vocabulary of stack overflow and immediately invoked function
- refactors to functional components

:sparkles: updates to react functional components

---

tools-and-resources/wireframes.md

- Adds syllabus page formatting
- Adds Kat's presentation video
- Adds more resources

:bento: adds video and additional resources to wireframing section

---

tools-and-resources/portfolio.md

- Adds Lisa's portfolio talk
- Adds Paul's recent portfolio talk
- Specifies use of github pages for HTML and CSS
- Adds render.com for static react pages
- Reworks weekly list to include week 7 for content created during PD week
- Adds more explanation around what a portfolio is
- Adds explicit instructions to start simple

:bento: adds new videos and expands content

---

.gitignore
ruby/blocks.md
ruby/hashes.md

- adds vscode config to gitignore
- adds more in depth explanations to blocks
- adds ranges to blocks
- adds explanation of CRUD to hashes
- adds notation for pulling all the keys or all the values from a hash

Ruby objects classes

---

javascript/arrays.md
javascript/classes.md
javascript/conditionals.md
javascript/functions-loops-arrays.md
javascript/functions.md
javascript/higher-order-functions.md
javascript/intro.md
javascript/jest.md
javascript/loops.md
javascript/objects.md
javascript/spread-operator.md
javascript/ternary.md
react/create-react-app.md
react/functional-props.md
react/intro.md
react/props.md
react/state-with-images.md
react/state.md
ruby/blocks.md
ruby/classes-objects.md
ruby/conditionals.md
ruby/hashes.md
ruby/inheritance.md
ruby/intro.md
ruby/rspec.md
ruby/textbased-challenge.md
tools-and-resources/linking-html-javascript.md

- adds a lot of consistency between units
- updates inheritance section
- refactors rspec section
- expands explanations
- no structural changes

Syllabus updates

---

external-api/fetch.md

- adds a lot of written content on API and API related context
- adds a new code example
- updates format for uniformity

:sparkles: adds vocab, content, and code evolutions

---

github/github.md

Adds the instruction to select the scope of 'workflow' when configuring the github token

:wrench: adds workflow to the list of scopes

---

README.md
cat-tinder/connecting/fetch-read.md

- moves fetch to cat tinder
- moves fetch to week 11

moves fetch to cat tinder

---

apartment-app/devise-react-in-rails.md

resolved error of missing arrow on line 211 of /apartment-app/devise-rails-in-react.md

resolving errors

---

javascript/conditionals.md
javascript/intro.md

- moves vocab terms from intro to conditionals
- moves operators lecture from intro to conditionals
- adds more intro challenges to fill space
- moves operation challenges to conditionals
- replaces var with const when appropriate

:art: moves Boolean operator explanations to conditionals section

---

cat-tinder/connecting/fetch-create.md
cat-tinder/connecting/fetch-read.md
cat-tinder/frontend/cat-create.md
cat-tinder/frontend/cat-read.md
cat-tinder/frontend/cat-testing.md
cat-tinder/frontend/intro.md
react/create-react-app.md
react/functional-props.md
react/inputs.md
react/intro.md
react/props.md
react/state.md

- updated react videos
- updated cat tinder frontend videos
- updated cat tinder fetch video
- updated video length notes

React videos

---

apartment-app/backend/devise.md

This is an incomplete very rough draft. Missing jwt-devise configs.

added jwt to devise section

---

apartment-app/connecting/connecting.md

breaks down the frontend process for authentication. 
This was very hard. :)

Jwt frontend

---

ruby/classes-objects.md
ruby/inheritance.md
ruby/rspec.md

- updated lecture videos and times during the audit
- changed "request" specification to "Ruby" specification for RSpec

updates lecture videos

---

javascript/intro.md

This is the audit for Unit 1 JavaScript Intro.

Javascript intro audit

---

javascript/classes.md
javascript/higher-order-functions.md
javascript/jest.md
javascript/objects.md

Classes 
- updated links for You Don't Know JS resources
- corrected spelling in challenges
HOF 
- updated lecture video
- corrected expected output in challenges
Jest 
- updated lecture video to one without enzyme 
Objects 
- updated challenges with last year's and this year's cohorts

javascript syllabus audit

---

cat-tinder/backend/api-cors.md
cat-tinder/backend/api-endpoints.md
cat-tinder/backend/api-intro.md
cat-tinder/backend/validations.md

updates lecture videos for cat tinder backend, minor rephrasing.

updates lecture videos for cat tinder backend

---

rails/active-record-intro.md

- grammar corrections
- video updated

syllabus audit for active record intro

---

cat-tinder/frontend/cat-read.md

updates cat tinder read section to include memory router in cat show testing

updates cat tinder read section with memory router

---

rails/controllers-routes-views.md

- Click the github classroom link
- Create team name
- Accept the assignment and refresh screen to allow github to create an empty repo.
- ***STOP! Just need the repo to stay empty.***

added process for github empty repo

---

rails/params.md

Corrected a minor typo in the params portion of the syllabus

changed greeting to greeter in syllabus
